import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/shared/components/shared/Navbar';
import BgPazzle from '@/shared/components/shared/BgPazzle';
import { MainFooter } from '@/shared/components/ui/main-footer';
import MobileNavbar from '@/shared/components/ui/mobile-navbar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col min-h-screen relative  ">
        <div className="absolute w-full h-full opacity-12  [background-image:radial-gradient(#000_1px,transparent_1px)] dark:[background-image:radial-gradient(white_1px,transparent_1px)] [background-size:30px_30px]"></div>
        <Navbar />
        <BgPazzle />

        {children}
        <MainFooter />
        <MobileNavbar />
      </div>
    </>
  );
}
