import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/shared/components/shared/Navbar';
import BgPazzle from '@/shared/components/shared/BgPazzle';
import { MainFooter } from '@/shared/components/ui/main-footer';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  {
    /* щоб не було скролу вниз футер і конетент поміщаються в висоту екрану 
    className="h-screen relative overflow-hidden flex flex-col justify-between" 
    */
  }
  return (
    <div className="h-screen relative sm:overflow-hidden sm:flex sm:flex-col sm:justify-between ">
      <div className="absolute w-full h-full opacity-12  [background-image:radial-gradient(#000_1px,transparent_1px)] dark:[background-image:radial-gradient(white_1px,transparent_1px)] [background-size:30px_30px]"></div>
      <Navbar />
      <BgPazzle />

      {children}
      <MainFooter />
    </div>
  );
}
