import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/shared/components/shared/Navbar';
import MobileNavbar from '@/shared/components/ui/mobile-navbar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <MobileNavbar />
    </>
  );
}
